CREATE DATABASE IF NOT EXISTS logistics_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE logistics_db;

DROP TABLE IF EXISTS `ORDER`;

DROP TABLE IF EXISTS `CUSTOMER`;

DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER` (
    UserId INT UNSIGNED AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Phone VARCHAR(15) NOT NULL,
    PRIMARY KEY (UserId)
);

CREATE TABLE `CUSTOMER` (
    UserId INT UNSIGNED NOT NULL,
    CustomerType VARCHAR(50) NOT NULL,
    PRIMARY KEY (UserId),
    CONSTRAINT fk_customer_user FOREIGN KEY (UserId) REFERENCES `USER` (UserId) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE `ORDER` (
    OrderId INT UNSIGNED AUTO_INCREMENT,
    OrderDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OrderStatus VARCHAR(20) NOT NULL DEFAULT 'Pending',
    PickupLocation VARCHAR(255) NOT NULL,
    DeliveryLocation VARCHAR(255) NOT NULL,
    FreightCost DECIMAL(12, 2) NOT NULL,
    CustomerId INT UNSIGNED NOT NULL,
    PRIMARY KEY (OrderId),
    CONSTRAINT fk_order_customer FOREIGN KEY (CustomerId) REFERENCES `CUSTOMER` (UserId) ON UPDATE CASCADE ON DELETE CASCADE
);